from enum import Enum


class BoardType(Enum):
	MONOTONE = 0
	TWO_TONE = 1
	RAINBOW = 2


class PotType(str, Enum):
	SRP = "SRP"
	THREE_BET = "THREE_BET"
	FOUR_BET = "FOUR_BET"


class ActionSequence(str, Enum):
	XX = "XX"
	XBC = "XBC"
	XBRC = "XBRC"
	BC = "BC"


class Runout(str, Enum):
	OVERCARD = "OVERCARD"
	FLUSH_COMPLETING = "FLUSH_COMPLETING"
	PAIRED = "PAIRED"
	OTHER = "OTHER"


class FlopRankTexture(str, Enum):
	TRIPS = "TRIPS"
	PAIRED = "PAIRED"
	UNPAIRED = "UNPAIRED"


class ShowdownType(str, Enum):
	CHECK_CHECK = "CHECK_CHECK"
	BET_CALL = "BET_CALL"
	RAISE_OCCURRED = "RAISE_OCCURRED"


class MadeHandType(str, Enum):
	STRAIGHT_FLUSH = "STRAIGHT_FLUSH"
	QUADS = "QUADS"
	FULL_HOUSE = "FULL_HOUSE"
	FLUSH = "FLUSH"
	STRAIGHT = "STRAIGHT"
	SET = "SET"
	TWO_PAIR = "TWO_PAIR"
	OVERPAIR = "OVERPAIR"
	TOP_PAIR = "TOP_PAIR"
	PAIR = "PAIR"
	ACE_HIGH = "ACE_HIGH"
	NO_MADE_HAND = "NO_MADE_HAND"


class DrawType(str, Enum):
	FLUSH_OESD = "FLUSH_OESD"
	FLUSH_GUTSHOT = "FLUSH_GUTSHOT"
	FLUSH_DRAW = "FLUSH_DRAW"
	OESD = "OESD"
	GUTSHOT = "GUTSHOT"
	NO_DRAW = "NO_DRAW"
